# Generated by Django 4.1.2 on 2022-11-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsisoftware',
            name='analysis_duration',
        ),
        migrations.RemoveField(
            model_name='hsisoftware',
            name='analysis_method',
        ),
        migrations.RemoveField(
            model_name='hsisoftware',
            name='imaging',
        ),
        migrations.RemoveField(
            model_name='hyperspectralimage',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hyper_spectral_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='multi_modal_data',
        ),
        migrations.AddField(
            model_name='hsisoftware',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hyperspectralimage',
            name='actual_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='hyperspectralimage',
            name='multi_modal_Data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.multimodaldata'),
        ),
        migrations.AddField(
            model_name='hyperspectralimage',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.patient'),
        ),
        migrations.AddField(
            model_name='hyperspectralimage',
            name='resolutionHeight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hyperspectralimage',
            name='resolutionWidth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imaging',
            name='analysis_duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imaging',
            name='analysis_method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imaging',
            name='hsi_software',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.hsisoftware'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientID',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='hyper_spectral_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.hyperspectralimage'),
        ),
        migrations.AlterField(
            model_name='hyperspectralimage',
            name='bands',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hyperspectralimage',
            name='frames',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hyperspectralimage',
            name='imaging_data',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hyperspectralimage',
            name='rgb_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.rgbimage'),
        ),
        migrations.AlterField(
            model_name='multimodaldata',
            name='biopsy',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multimodaldata',
            name='postop_mri',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='multimodaldata',
            name='preop_mri',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='rgbimage',
            name='anatomical_annot',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
