# Generated by Django 4.1.2 on 2022-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_remove_hsisoftware_analysis_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hyperspectralimage',
            old_name='resolutionHeight',
            new_name='resolution_height',
        ),
        migrations.RenameField(
            model_name='hyperspectralimage',
            old_name='resolutionWidth',
            new_name='resolution_width',
        ),
        migrations.AddField(
            model_name='hyperspectralimage',
            name='image_filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hyperspectralimage',
            name='resolution_depth',
            field=models.IntegerField(null=True),
        ),
    ]
